workspace(name = "BullseyeSample")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "grab_bazel_common",
    remote = "https://github.com/grab/grab-bazel-common",
    commit = "540432b688186b0b6f52d6c49d116bf2cef82f3d"
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_android",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
)

load("@grab_bazel_common//:workspace_defs.bzl", "android_tools")

android_tools(
    commit = "f74ef90479383a38cef1af33d28a3253031e00c1",
    remote = "https://github.com/grab/grab-bazel-common.git",
)

http_archive(
    name = "rules_jvm_external",
    sha256 = "f36441aa876c4f6427bfb2d1f2d723b48e9d930b62662bf723ddfb8fc80f0140",
    strip_prefix = "rules_jvm_external-4.1",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/4.1.zip",
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    artifacts = [
        "androidx.appcompat:appcompat:1.4.1",
        "androidx.constraintlayout:constraintlayout:2.1.3",
        "androidx.core:core-ktx:1.7.0",
        "androidx.core:core-splashscreen:1.0.0-beta01",
        "androidx.databinding:viewbinding:7.1.2",
        "com.google.android.material:material:1.5.0",
        "org.jacoco:org.jacoco.ant:0.8.3",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10",
        "junit:junit:4.13.2",
        "androidx.test.ext:junit:1.1.3",
        "androidx.test.espresso:espresso-core:3.4.0",
    ],
    fail_on_missing_checksum = False,
    jetify_include_list = [
        "androidx.appcompat:appcompat",
        "androidx.constraintlayout:constraintlayout",
        "androidx.core:core-ktx",
        "androidx.core:core-splashscreen",
        "androidx.databinding:viewbinding",
        "com.google.android.material:material",
        "org.jacoco:org.jacoco.ant",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
        "junit:junit",
        "androidx.test.ext:junit",
        "androidx.test.espresso:espresso-core",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    resolve_timeout = 600,
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = "da0e6e1543fcc79e93d4d93c3333378f3bd5d29e82c1bc2518de0dbe048e6598",
    url = "https://github.com/bazelbuild/rules_kotlin/releases/download/%s/rules_kotlin_release.tgz" % "legacy-1.4.0-rc3",
)

KOTLIN_VERSION = "1.4.21"

KOTLINC_RELEASE_SHA = "46720991a716e90bfc0cf3f2c81b2bd735c14f4ea6a5064c488e04fd76e6b6c7"

KOTLINC_RELEASE = {
    "urls": [
        "https://github.com/JetBrains/kotlin/releases/download/v{v}/kotlin-compiler-{v}.zip".format(v = KOTLIN_VERSION),
    ],
    "sha256": KOTLINC_RELEASE_SHA,
}

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories")

kotlin_repositories(compiler_release = KOTLINC_RELEASE)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_register_toolchains")

kt_register_toolchains()

android_sdk_repository(
    name = "androidsdk",
    api_level = 32,
    build_tools_version = "30.0.3",
)

